name: build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build

    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu, windows]

    permissions:
      contents: write

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-03-14
    
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: install build deps
        run: >
          sudo apt-get update && sudo apt-get install --no-install-recommends -y
          cmake openssl libatk1.0-dev libgtk-3-dev
          libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev
          libxfixes-dev libpango1.0-dev libgl1-mesa-dev libglu1-mesa-dev libxdo-dev
        if: ${{ matrix.os == 'ubuntu' }}
      
      - name: build release (linux/windows)
        run: cargo build --release

      # IDK if this is proper
      - name: rename Windows artifact
        run: mv "target/release/twowalltwotaker.exe" "target/release/2wall2taker-windows.exe"
        if: ${{ matrix.os == 'windows' }}
       
      - name: rename Linux artifact
        run: mv "target/release/twowalltwotaker" "target/release/2wall2taker-linux-x11"
        if: ${{ matrix.os == 'ubuntu' }}

      - name: publish artifact
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/2wall2taker-*