name: build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build

    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu, windows, macos]

    permissions:
      contents: write

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-03-14
    
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: install build deps
        run: >
          sudo apt-get update && sudo apt-get install --no-install-recommends -y
          cmake openssl
          libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev
          libxfixes-dev libpango1.0-dev libgl1-mesa-dev libglu1-mesa-dev libxdo-dev
        if: ${{ matrix.os == 'ubuntu' }}
      
      - name: build release (linux/windows)
        run: cargo build --release
        if: ${{ matrix.os != 'macos' }}

      # Build a fat binary with universal2 for x86 and ARM macOS support
      - name: build release (macos)
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
          cargo install universal2 --version 0.0.1
          cargo universal2
          mkdir -p target/release
          mv target/universal2-apple-darwin/release/twowalltwotaker target/release/2wall2taker-macos-fat
        if: ${{ matrix.os == 'macos' }}

      # IDK if this is proper
      - name: rename Windows artifact
        run: mv "target/release/twowalltwotaker.exe" "target/release/2wall2taker-windows.exe"
        if: ${{ matrix.os == 'windows' }}
       
      - name: rename Linux artifact
        run: mv "target/release/twowalltwotaker" "target/release/2wall2taker-linux-x11"
        if: ${{ matrix.os == 'ubuntu' }}

      - name: publish artifact
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/2wall2taker-*